services:
  client:
    build: client
    depends_on:
      - mongo-backend
      - server
    volumes:
      - ./client:/opt/mern-stack
      - /opt/mern-stack/node_modules
    restart: always
    ports:
      - 3000:3000
    
  server:
    build: server
    depends_on:
      - mongo-backend
    environment:
      MONGO_DB=mongodb://<mongo-user>:<mongo-pass>@mongo-backend:27017
      PORT=5001
    env_file:
      ./server/config.env
    networks:
      - MONGO
    volumes:
      - ./server/src:/opt/mern-stack/src
      - /opt/mern-stack/node_modules
    restart: always
    ports:
      - 5001:5001   

  mongo-backend:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - db-data1:/data/db
    networks:
      - MONGO
    environment:
      MONGO_INITDB_ROOT_USERNAME: <mongo-user>
      MONGO_INITDB_ROOT_PASSWORD: <mongo-pass>

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8050:8081
    depends_on:
      - mongo-backend
    networks:
      - MONGO
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://<mongo-user>:<mongo-pass>@mongo-backend:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: <mongo-user>
      ME_CONFIG_MONGODB_ADMINPASSWORD: <mongo-pass>

volumes:
  db-data1:

networks:
  MONGO:
    name: MONGO
